version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres:15.3-bookworm
    environment:
      POSTGRES_DB: "tasks1db"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes/pgserver:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d tasks1db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.3
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "gureev_e@1cps.ru"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

